# Explicit imports from each module (replacing star imports for pyflakes compatibility)
from tasks.ingestion_task import (
    crawl_article_task,
    run_ingestion,
    auto_repair_sources_task,
)
from tasks.intelligence import (
    standardize_article_style_task,
    detect_global_story_task,
    summarize_article_task,
    synthesize_cluster_task,
    auto_summarize_task,
    extract_entities_task,
    classify_topics_task,
    recluster_recent_articles_task,
    generate_cluster_metadata_task,
    backfill_cover_art_single_task,
    backfill_cover_art_task,
    generate_embeddings_task,
    discover_storylines_task,
)
from tasks.delivery import (
    generate_daily_brief_task,
    send_daily_digest_task,
    send_profile_briefings_task,
    send_profile_weekly_digests_task,
    send_profile_breaking_alerts_task,
    send_newsletter_task,
)
from tasks.maintenance import (
    run_prune_db,
    refresh_global_headlines_task,
)

# Explicitly import private delivery functions for test accessibility
from tasks.delivery import (
    _load_daily_brief_clusters,
    _load_weekly_topic_engagement,
    _load_weekly_source_engagement,
    _load_weekly_cluster_engagement,
    _load_active_delivery_rows,
    _load_cluster_alert_material,
    _load_delivery_kind_performance,
    _load_breaking_target_performance,
    _classify_alert_candidate,
    _select_breaking_cluster_for_profile,
    _record_delivery_tracking_event,
    _send_ntfy_message,
    _build_weekly_digest_sections,
    _normalize_synced_profile_for_delivery,
    _call_ai,
    _build_daily_brief_context,
    _select_profile_brief_clusters,
    _select_profile_weekly_clusters,
    _build_profile_briefing_message,
    _build_profile_weekly_digest_message,
    _load_weekly_digest_clusters,
    _load_recent_breaking_clusters,
)

# Explicitly re-export for clarity and auto-discovery
__all__ = [
    "crawl_article_task",
    "run_ingestion",
    "auto_repair_sources_task",
    "standardize_article_style_task",
    "detect_global_story_task",
    "summarize_article_task",
    "synthesize_cluster_task",
    "auto_summarize_task",
    "extract_entities_task",
    "classify_topics_task",
    "recluster_recent_articles_task",
    "refresh_global_headlines_task",
    "generate_cluster_metadata_task",
    "backfill_cover_art_single_task",
    "backfill_cover_art_task",
    "generate_embeddings_task",
    "discover_storylines_task",
    "generate_daily_brief_task",
    "send_daily_digest_task",
    "send_profile_briefings_task",
    "send_profile_weekly_digests_task",
    "send_profile_breaking_alerts_task",
    "send_newsletter_task",
    "run_prune_db",
    # Private functions for test accessibility
    "_load_daily_brief_clusters",
    "_load_weekly_topic_engagement",
    "_load_weekly_source_engagement",
    "_load_weekly_cluster_engagement",
    "_load_active_delivery_rows",
    "_load_cluster_alert_material",
    "_load_delivery_kind_performance",
    "_load_breaking_target_performance",
    "_classify_alert_candidate",
    "_select_breaking_cluster_for_profile",
    "_record_delivery_tracking_event",
    "_send_ntfy_message",
    "_build_weekly_digest_sections",
    "_normalize_synced_profile_for_delivery",
    "_call_ai",
    "_build_daily_brief_context",
    "_select_profile_brief_clusters",
    "_select_profile_weekly_clusters",
    "_build_profile_briefing_message",
    "_build_profile_weekly_digest_message",
    "_load_weekly_digest_clusters",
    "_load_recent_breaking_clusters",
]
