import asyncio
import logging

from core.database import db_manager as db
from tasks.ingestion_task import crawl_article_task

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("presek.backfill")


async def backfill():
    # Find articles with image_url but no local_image_path
    # Exclude placeholders generated by the system if we want
    rows = db.execute(
        """
        SELECT id, link
        FROM articles
        WHERE image_url IS NOT NULL
          AND local_image_path IS NULL
          AND image_url NOT LIKE '/static/%'
        ORDER BY created_at DESC
        LIMIT 500
    """
    )

    if not rows:
        log.info("No articles found for image backfill.")
        return

    log.info(f"Queueing crawl_article_task for {len(rows)} articles...")

    for row in rows:
        # We use .delay() to queue it in Celery
        crawl_article_task.delay(row["id"], row["link"])

    log.info("Backfill tasks queued successfully.")


if __name__ == "__main__":
    asyncio.run(backfill())
