# Local-only nginx stub_status for prometheus nginx exporter.
server {
    listen 127.0.0.1:8080;
    server_name localhost;

    access_log off;

    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
    }
}
