"""Centralized runtime limits for API, security middleware, and worker backpressure."""

import os

from core.config import API_MAX_PAGE, API_MAX_Q_LEN

MAX_REQUEST_BODY_SIZE = 10 * 1024 * 1024  # 10 MB
MAX_QUERY_PARAM_LENGTH = API_MAX_Q_LEN
MAX_HEADER_VALUE_LENGTH = 2000

INTEL_QUEUE_SOFT_DEFER_LIMIT = int(os.environ.get("INTEL_QUEUE_SOFT_DEFER_LIMIT", "80"))
INTEL_QUEUE_SECONDARY_DEFER_LIMIT = int(os.environ.get("INTEL_QUEUE_SECONDARY_DEFER_LIMIT", "150"))
INTEL_QUEUE_FULL_DEFER_LIMIT = int(os.environ.get("INTEL_QUEUE_FULL_DEFER_LIMIT", "800"))
BACKFILL_QUEUE_DEPTH_LIMIT = int(os.environ.get("BACKFILL_QUEUE_DEPTH_LIMIT", "100"))

CELERY_QUEUE_WARN_DEPTH = int(os.environ.get("CELERY_QUEUE_WARN_DEPTH", "150"))
CELERY_QUEUE_CRITICAL_DEPTH = int(os.environ.get("CELERY_QUEUE_CRITICAL_DEPTH", "500"))

CRAWL_QUEUE_SOFT_LIMIT = int(os.environ.get("CRAWL_QUEUE_SOFT_LIMIT", "150"))
CRAWL_QUEUE_DEFER_LIMIT = int(os.environ.get("CRAWL_QUEUE_DEFER_LIMIT", "400"))
CRAWL_DISPATCH_CAP = int(os.environ.get("CRAWL_DISPATCH_CAP", "30"))
CRAWL_CATCH_UP_LIMIT = int(os.environ.get("CRAWL_CATCH_UP_LIMIT", "120"))

FACT_GROUNDING_MAX_UNGROUNDED = int(os.environ.get("FACT_GROUNDING_MAX_UNGROUNDED", "2"))
FACT_GROUNDING_MAX_UNGROUNDED_FAST = int(os.environ.get("FACT_GROUNDING_MAX_UNGROUNDED_FAST", "4"))

# Synthesis routing profiles: balanced (default), quality, cost
SYNTHESIS_PROFILE = (os.environ.get("SYNTHESIS_PROFILE") or "balanced").strip().lower()

SYNTHESIS_QUALITY_MIN_LOCAL = float(os.environ.get("SYNTHESIS_QUALITY_MIN_LOCAL", "0.65"))
SYNTHESIS_QUALITY_MIN_MISTRAL_SMALL = float(os.environ.get("SYNTHESIS_QUALITY_MIN_MISTRAL_SMALL", "0.70"))
SYNTHESIS_QUALITY_MIN_MISTRAL_LARGE = float(os.environ.get("SYNTHESIS_QUALITY_MIN_MISTRAL_LARGE", "0.75"))
SYNTHESIS_QUALITY_MIN_NVIDIA = float(os.environ.get("SYNTHESIS_QUALITY_MIN_NVIDIA", "0.70"))

SYNTHESIS_MK_TRANSLATE_FROM_SR = os.environ.get("SYNTHESIS_MK_TRANSLATE_FROM_SR", "true").lower() == "true"
SYNTHESIS_GEMMA_BEFORE_DETERMINISTIC = (
    os.environ.get("SYNTHESIS_GEMMA_BEFORE_DETERMINISTIC", "true").lower() == "true"
)

FAST_SYNTHESIS_STUCK_HOURS = int(os.environ.get("FAST_SYNTHESIS_STUCK_HOURS", "24"))
FAST_SYNTHESIS_PENDING_TTL_SECONDS = int(os.environ.get("FAST_SYNTHESIS_PENDING_TTL_SECONDS", str(48 * 3600)))
FAST_SYNTHESIS_UPGRADE_FORCE_AFTER_DEFERS = (
    os.environ.get("FAST_SYNTHESIS_UPGRADE_FORCE_AFTER_DEFERS", "true").lower() == "true"
)
FAST_SYNTHESIS_UPGRADE_QUEUE = os.environ.get("FAST_SYNTHESIS_UPGRADE_QUEUE", "maintenance")
FAST_SYNTHESIS_UPGRADE_SWEEP_LIMIT = int(os.environ.get("FAST_SYNTHESIS_UPGRADE_SWEEP_LIMIT", "25"))
FALLBACK_SYNTHESIS_REFRESH_LIMIT = int(os.environ.get("FALLBACK_SYNTHESIS_REFRESH_LIMIT", "30"))
LOW_SCORE_SYNTHESIS_MIN = float(os.environ.get("LOW_SCORE_SYNTHESIS_MIN", "0.75"))
LOW_SCORE_SYNTHESIS_REFRESH_LIMIT = int(os.environ.get("LOW_SCORE_SYNTHESIS_REFRESH_LIMIT", "20"))
SYNTHESIS_REFRESH_HOURLY_CAP = int(os.environ.get("SYNTHESIS_REFRESH_HOURLY_CAP", "120"))
LOCAL_LLM_LOCK_TIMEOUT_SECONDS = int(os.environ.get("LOCAL_LLM_LOCK_TIMEOUT_SECONDS", "300"))
LOCAL_LLM_SYNTHESIS_LOCK_TIMEOUT_SECONDS = int(
    os.environ.get("LOCAL_LLM_SYNTHESIS_LOCK_TIMEOUT_SECONDS", "420")
)
ROUTER_FALLBACK_PRESSURE_LOCAL = os.environ.get("ROUTER_FALLBACK_PRESSURE_LOCAL", "true").lower() == "true"
LOCAL_SYNTHESIS_SIMPLIFIED_SCHEMA = os.environ.get("LOCAL_SYNTHESIS_SIMPLIFIED_SCHEMA", "true").lower() == "true"
