# Re-exporting functions for backward compatibility
# pylint: disable=unused-import
from .cache import (
    cached_response,
    check_rate_limit,
    delete_cache,
    delete_cache_prefix,
    event_stream,
    publish_event,
    record_runtime_event,
    redis_client,
    set_cache,
)
from .db_helpers import get_source_registry
from .network import (
    UnsafeFetchError,
    _peer_ip,
    _peer_is_public,
    _resolve_public_ips,
    fetch_public_bytes,
    get_dominant_color,
)
from .ranking import (
    _cluster_title_overlap,
    annotate_cluster_articles,
    assess_cluster_synthesis_freshness,
    build_cluster_source_signals,
    build_editor_analytics_payload,
    build_read_next_clusters,
    build_source_reputation_rows,
    get_source_effective_weight,
    get_source_health_map,
    get_source_quality_multiplier,
    get_source_trust_label,
    is_balanced,
    rank_articles_in_cluster,
    score_cluster,
    score_cluster_for_homepage,
    score_cluster_for_synthesis,
)
from .text import calculate_reading_time, format_sources
from .time import DateTimeEncoder, _coerce_datetime

__all__ = [
    "cached_response",
    "check_rate_limit",
    "delete_cache",
    "delete_cache_prefix",
    "event_stream",
    "publish_event",
    "record_runtime_event",
    "redis_client",
    "set_cache",
    "get_source_registry",
    "_peer_ip",
    "_peer_is_public",
    "UnsafeFetchError",
    "fetch_public_bytes",
    "_resolve_public_ips",
    "get_dominant_color",
    "_cluster_title_overlap",
    "annotate_cluster_articles",
    "assess_cluster_synthesis_freshness",
    "build_cluster_source_signals",
    "build_editor_analytics_payload",
    "build_read_next_clusters",
    "build_source_reputation_rows",
    "get_source_effective_weight",
    "get_source_health_map",
    "get_source_quality_multiplier",
    "get_source_trust_label",
    "is_balanced",
    "rank_articles_in_cluster",
    "score_cluster",
    "score_cluster_for_homepage",
    "score_cluster_for_synthesis",
    "calculate_reading_time",
    "format_sources",
    "DateTimeEncoder",
    "_coerce_datetime",
]
